### ISSUE TITLE
Provide .sln in repository

### ISSUE THREAD

**Issue by Cylix** [thibault-martinez/iota.lib.cpp#213]
as the title says

**Comment by Hemofektik** [comment]
May I ask why this is necessary when having cmake based project which can generate sln files perfectly fine?

**Comment by Hemofektik** [comment]
I have seen this in many open source projects as well but often the sln file was not up to date because as you mentioned it is twice the effort to maintain. And it's not only the sln file that has to be maintained but also all the vcxproj files that are necessary to build all the components. Every pull request needs extra time and perseverance to check and maintain the sln/vcxproj files.

I myself mostly work on windows using Visual Studio and switched two years ago to fully CMake because the sln/vcxproj files it generates are much more easy to maintain via the cmake files. Adding files, adding a library, setting custom compiler flags, etc. are much more easy to handle compared to using the endless error prone project settings "wizards" of Visual Studio.

One other problem some of the open source projects have that provide both cmake and sln is that the cmake is not maintained to work with windows. That means that people like me who usually build everything with cmake have to link in the vcxproj files within a custom branch of my projects' cmake file using cmake's special Visual Studio Macros.

Of course I would not like to force my working style upon other windows developers but it is 2018 and cmake is well established in most open source projects and reading one page of the cmake docs is not too much to ask for.

This is just my experience and opinion.  I would just try to reduce redundancies as much as possible.

Regards
Richard

**Comment by Cylix** [comment]
I 100% with you 👍 

Our main focus is definitely the CMake as it makes the build chain portable and flexible.
We will always prioritize the CMake build and highly recommend it to new users.

The .sln will be proposed as an alternative solution for developers that do not have the experience working with that kind of tools.
Even though it requires more maintainability, it makes the library more accessible which will be great if it can help developing new great applications around the IOTA technology.

Concerning the possible outdated .sln/.vcxproj files, this can't happen.
We spent a large amount of time setting up CI tools, making it possible to verify compilations on different platforms.
We still have some issues concerning Appveyor configuration on 32 bits platform, but the point is that when the .sln will be added, we have builds configured for both CMake and .sln.
This will allow us to control whether or not the .sln is outdated and requires change.

I agree concerning the PR however. Not everyone has a windows environment to make the change.
What I usually do is to make the update by myself by pushing to the given PR (as a maintainer, GitHub allows you to push to forks, thus updating the PR).

So, though the .sln is not our top priority and will not be a recommended tool, I think it can be helpful to provide it at the beginning, then to suppress it on the long run.

@thibault-martinez do you have any input on this?

Best

**Comment by thibault-martinez** [comment]
Well, I'm not really familiar with the .sln solution.

My thoughts on this are that we should promote the CMake solution as it is portable and will always be up to date; thus, the .sln will never be a priority for us.

However, I am not against the idea of providing a base .sln hoping that it will be community updated :)

**Comment by Cylix** [comment]
Turns out cpr dependency does not provide any MSVC solution in their repository, as well as its sub-dependency mongoose.
This makes it impossible to provide an MSVC solution without creating an MSVC solution for their project, making it not maintainable.

I keep this issue open in case there is changes in their repositories in the future.

I'll raise an issue in their respective repositories to see if they are open to the addition of a MSVC solution. If so I can provide it and then reference it from our repository.
Otherwise, the alternative would be to have these MSVC solutions inside our repositories which is not the right way to go as we will then be responsible of maintaining the MSVC solutions of other projects.
