### ISSUE TITLE
tritsToBytes coverage

### ISSUE THREAD

**Issue by thibault-martinez** [thibault-martinez/iota.lib.cpp#233]
Hi @mistersandman, hope you're doing well.

I was watching our code coverage and saw that the following lines are never triggered.

https://coveralls.io/builds/15601574/source?filename=source%2Ftypes%2Ftrinary.cpp#L127
https://coveralls.io/builds/15601574/source?filename=source%2Ftypes%2Ftrinary.cpp#L138

Out of 508,392 calls to tritsToBytes in our tests they are never actually called.
Could you provide an input which would execute them ?
If not, are they actually useful to the function ?
Can they be safely removed ?

Thanks in advance,

**Comment by mistersandman** [comment]
Hi @thibault-martinez, yes I am doing fine and hope you do so too!

These conditional code lines cover really rare cases so I‘m actually not surprised, they were never executed, but i think they are important and cannot be left out. I will try to come up with testcases that cover them, but I can only do so no earlier than sunday, since I‘m busy until then.

**Comment by thibault-martinez** [comment]
No problem take your time, we're not in a hurry, thanks.

**Comment by thibault-martinez** [comment]
Closed by #244, thanks again @mistersandman :)
